// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: attributes_storage.proto

package storage

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/gogo/protobuf/types"
	github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type AttributesQueryParameters struct {
	// Optional. The workspace ID to filter traces.
	WorkspaceId          string    `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	ServiceName          string    `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	OperationName        string    `protobuf:"bytes,3,opt,name=operation_name,json=operationName,proto3" json:"operation_name,omitempty"`
	StartTimeMin         time.Time `protobuf:"bytes,4,opt,name=start_time_min,json=startTimeMin,proto3,stdtime" json:"start_time_min"`
	StartTimeMax         time.Time `protobuf:"bytes,5,opt,name=start_time_max,json=startTimeMax,proto3,stdtime" json:"start_time_max"`
	Limit                int32     `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AttributesQueryParameters) Reset()         { *m = AttributesQueryParameters{} }
func (m *AttributesQueryParameters) String() string { return proto.CompactTextString(m) }
func (*AttributesQueryParameters) ProtoMessage()    {}
func (*AttributesQueryParameters) Descriptor() ([]byte, []int) {
	return fileDescriptor_c16f9b9e04e990b0, []int{0}
}
func (m *AttributesQueryParameters) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AttributesQueryParameters) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AttributesQueryParameters.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AttributesQueryParameters) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttributesQueryParameters.Merge(m, src)
}
func (m *AttributesQueryParameters) XXX_Size() int {
	return m.Size()
}
func (m *AttributesQueryParameters) XXX_DiscardUnknown() {
	xxx_messageInfo_AttributesQueryParameters.DiscardUnknown(m)
}

var xxx_messageInfo_AttributesQueryParameters proto.InternalMessageInfo

func (m *AttributesQueryParameters) GetWorkspaceId() string {
	if m != nil {
		return m.WorkspaceId
	}
	return ""
}

func (m *AttributesQueryParameters) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *AttributesQueryParameters) GetOperationName() string {
	if m != nil {
		return m.OperationName
	}
	return ""
}

func (m *AttributesQueryParameters) GetStartTimeMin() time.Time {
	if m != nil {
		return m.StartTimeMin
	}
	return time.Time{}
}

func (m *AttributesQueryParameters) GetStartTimeMax() time.Time {
	if m != nil {
		return m.StartTimeMax
	}
	return time.Time{}
}

func (m *AttributesQueryParameters) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

// Request object to get indexed attribute names.
// "Indexed" attributes are the most frequently used attributes in the trace data,
// which are often used/allowed for querying and filtering.
type GetIndexedAttributesNamesRequest struct {
	// Optional. The workspace ID to filter Operations.
	WorkspaceId          string                     `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	ServiceName          string                     `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	OperationName        string                     `protobuf:"bytes,3,opt,name=operation_name,json=operationName,proto3" json:"operation_name,omitempty"`
	Query                *AttributesQueryParameters `protobuf:"bytes,4,opt,name=query,proto3" json:"query,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *GetIndexedAttributesNamesRequest) Reset()         { *m = GetIndexedAttributesNamesRequest{} }
func (m *GetIndexedAttributesNamesRequest) String() string { return proto.CompactTextString(m) }
func (*GetIndexedAttributesNamesRequest) ProtoMessage()    {}
func (*GetIndexedAttributesNamesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c16f9b9e04e990b0, []int{1}
}
func (m *GetIndexedAttributesNamesRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetIndexedAttributesNamesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetIndexedAttributesNamesRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetIndexedAttributesNamesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetIndexedAttributesNamesRequest.Merge(m, src)
}
func (m *GetIndexedAttributesNamesRequest) XXX_Size() int {
	return m.Size()
}
func (m *GetIndexedAttributesNamesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetIndexedAttributesNamesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetIndexedAttributesNamesRequest proto.InternalMessageInfo

func (m *GetIndexedAttributesNamesRequest) GetWorkspaceId() string {
	if m != nil {
		return m.WorkspaceId
	}
	return ""
}

func (m *GetIndexedAttributesNamesRequest) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *GetIndexedAttributesNamesRequest) GetOperationName() string {
	if m != nil {
		return m.OperationName
	}
	return ""
}

func (m *GetIndexedAttributesNamesRequest) GetQuery() *AttributesQueryParameters {
	if m != nil {
		return m.Query
	}
	return nil
}

// Response object to get attribute names.
type GetAttributesNamesResponse struct {
	Names                []string `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAttributesNamesResponse) Reset()         { *m = GetAttributesNamesResponse{} }
func (m *GetAttributesNamesResponse) String() string { return proto.CompactTextString(m) }
func (*GetAttributesNamesResponse) ProtoMessage()    {}
func (*GetAttributesNamesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c16f9b9e04e990b0, []int{2}
}
func (m *GetAttributesNamesResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetAttributesNamesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetAttributesNamesResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetAttributesNamesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAttributesNamesResponse.Merge(m, src)
}
func (m *GetAttributesNamesResponse) XXX_Size() int {
	return m.Size()
}
func (m *GetAttributesNamesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAttributesNamesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAttributesNamesResponse proto.InternalMessageInfo

func (m *GetAttributesNamesResponse) GetNames() []string {
	if m != nil {
		return m.Names
	}
	return nil
}

// Request object to get top-K attribute values.
type GetTopKAttributeValuesRequest struct {
	WorkspaceId   string                     `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	ServiceName   string                     `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	OperationName string                     `protobuf:"bytes,3,opt,name=operation_name,json=operationName,proto3" json:"operation_name,omitempty"`
	AttributeName string                     `protobuf:"bytes,4,opt,name=attribute_name,json=attributeName,proto3" json:"attribute_name,omitempty"`
	Query         *AttributesQueryParameters `protobuf:"bytes,5,opt,name=query,proto3" json:"query,omitempty"`
	// Optional. Number of values to return. If unset or <=0, the server chooses a default.
	K                    int32    `protobuf:"varint,6,opt,name=k,proto3" json:"k,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTopKAttributeValuesRequest) Reset()         { *m = GetTopKAttributeValuesRequest{} }
func (m *GetTopKAttributeValuesRequest) String() string { return proto.CompactTextString(m) }
func (*GetTopKAttributeValuesRequest) ProtoMessage()    {}
func (*GetTopKAttributeValuesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c16f9b9e04e990b0, []int{3}
}
func (m *GetTopKAttributeValuesRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetTopKAttributeValuesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetTopKAttributeValuesRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetTopKAttributeValuesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTopKAttributeValuesRequest.Merge(m, src)
}
func (m *GetTopKAttributeValuesRequest) XXX_Size() int {
	return m.Size()
}
func (m *GetTopKAttributeValuesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTopKAttributeValuesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTopKAttributeValuesRequest proto.InternalMessageInfo

func (m *GetTopKAttributeValuesRequest) GetWorkspaceId() string {
	if m != nil {
		return m.WorkspaceId
	}
	return ""
}

func (m *GetTopKAttributeValuesRequest) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *GetTopKAttributeValuesRequest) GetOperationName() string {
	if m != nil {
		return m.OperationName
	}
	return ""
}

func (m *GetTopKAttributeValuesRequest) GetAttributeName() string {
	if m != nil {
		return m.AttributeName
	}
	return ""
}

func (m *GetTopKAttributeValuesRequest) GetQuery() *AttributesQueryParameters {
	if m != nil {
		return m.Query
	}
	return nil
}

func (m *GetTopKAttributeValuesRequest) GetK() int32 {
	if m != nil {
		return m.K
	}
	return 0
}

// Response object to get top-K attribute values.
type GetTopKAttributeValuesResponse struct {
	Values               []string `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTopKAttributeValuesResponse) Reset()         { *m = GetTopKAttributeValuesResponse{} }
func (m *GetTopKAttributeValuesResponse) String() string { return proto.CompactTextString(m) }
func (*GetTopKAttributeValuesResponse) ProtoMessage()    {}
func (*GetTopKAttributeValuesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c16f9b9e04e990b0, []int{4}
}
func (m *GetTopKAttributeValuesResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetTopKAttributeValuesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetTopKAttributeValuesResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetTopKAttributeValuesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTopKAttributeValuesResponse.Merge(m, src)
}
func (m *GetTopKAttributeValuesResponse) XXX_Size() int {
	return m.Size()
}
func (m *GetTopKAttributeValuesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTopKAttributeValuesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTopKAttributeValuesResponse proto.InternalMessageInfo

func (m *GetTopKAttributeValuesResponse) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

// Request object to get bottom-K attribute values.
type GetBottomKAttributeValuesRequest struct {
	WorkspaceId   string                     `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	ServiceName   string                     `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	OperationName string                     `protobuf:"bytes,3,opt,name=operation_name,json=operationName,proto3" json:"operation_name,omitempty"`
	AttributeName string                     `protobuf:"bytes,4,opt,name=attribute_name,json=attributeName,proto3" json:"attribute_name,omitempty"`
	Query         *AttributesQueryParameters `protobuf:"bytes,5,opt,name=query,proto3" json:"query,omitempty"`
	// Optional. Number of values to return. If unset or <=0, the server chooses a default.
	K                    int32    `protobuf:"varint,6,opt,name=k,proto3" json:"k,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBottomKAttributeValuesRequest) Reset()         { *m = GetBottomKAttributeValuesRequest{} }
func (m *GetBottomKAttributeValuesRequest) String() string { return proto.CompactTextString(m) }
func (*GetBottomKAttributeValuesRequest) ProtoMessage()    {}
func (*GetBottomKAttributeValuesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c16f9b9e04e990b0, []int{5}
}
func (m *GetBottomKAttributeValuesRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetBottomKAttributeValuesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetBottomKAttributeValuesRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetBottomKAttributeValuesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBottomKAttributeValuesRequest.Merge(m, src)
}
func (m *GetBottomKAttributeValuesRequest) XXX_Size() int {
	return m.Size()
}
func (m *GetBottomKAttributeValuesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBottomKAttributeValuesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBottomKAttributeValuesRequest proto.InternalMessageInfo

func (m *GetBottomKAttributeValuesRequest) GetWorkspaceId() string {
	if m != nil {
		return m.WorkspaceId
	}
	return ""
}

func (m *GetBottomKAttributeValuesRequest) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *GetBottomKAttributeValuesRequest) GetOperationName() string {
	if m != nil {
		return m.OperationName
	}
	return ""
}

func (m *GetBottomKAttributeValuesRequest) GetAttributeName() string {
	if m != nil {
		return m.AttributeName
	}
	return ""
}

func (m *GetBottomKAttributeValuesRequest) GetQuery() *AttributesQueryParameters {
	if m != nil {
		return m.Query
	}
	return nil
}

func (m *GetBottomKAttributeValuesRequest) GetK() int32 {
	if m != nil {
		return m.K
	}
	return 0
}

// Response object to get bottom-K attribute values.
type GetBottomKAttributeValuesResponse struct {
	Values               []string `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBottomKAttributeValuesResponse) Reset()         { *m = GetBottomKAttributeValuesResponse{} }
func (m *GetBottomKAttributeValuesResponse) String() string { return proto.CompactTextString(m) }
func (*GetBottomKAttributeValuesResponse) ProtoMessage()    {}
func (*GetBottomKAttributeValuesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c16f9b9e04e990b0, []int{6}
}
func (m *GetBottomKAttributeValuesResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetBottomKAttributeValuesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetBottomKAttributeValuesResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetBottomKAttributeValuesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBottomKAttributeValuesResponse.Merge(m, src)
}
func (m *GetBottomKAttributeValuesResponse) XXX_Size() int {
	return m.Size()
}
func (m *GetBottomKAttributeValuesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBottomKAttributeValuesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBottomKAttributeValuesResponse proto.InternalMessageInfo

func (m *GetBottomKAttributeValuesResponse) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

func init() {
	proto.RegisterType((*AttributesQueryParameters)(nil), "jaeger.storage.v2.AttributesQueryParameters")
	proto.RegisterType((*GetIndexedAttributesNamesRequest)(nil), "jaeger.storage.v2.GetIndexedAttributesNamesRequest")
	proto.RegisterType((*GetAttributesNamesResponse)(nil), "jaeger.storage.v2.GetAttributesNamesResponse")
	proto.RegisterType((*GetTopKAttributeValuesRequest)(nil), "jaeger.storage.v2.GetTopKAttributeValuesRequest")
	proto.RegisterType((*GetTopKAttributeValuesResponse)(nil), "jaeger.storage.v2.GetTopKAttributeValuesResponse")
	proto.RegisterType((*GetBottomKAttributeValuesRequest)(nil), "jaeger.storage.v2.GetBottomKAttributeValuesRequest")
	proto.RegisterType((*GetBottomKAttributeValuesResponse)(nil), "jaeger.storage.v2.GetBottomKAttributeValuesResponse")
}

func init() { proto.RegisterFile("attributes_storage.proto", fileDescriptor_c16f9b9e04e990b0) }

var fileDescriptor_c16f9b9e04e990b0 = []byte{
	// 535 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe4, 0x94, 0x31, 0x6f, 0xd3, 0x40,
	0x14, 0xc7, 0x7b, 0x49, 0x1d, 0xe8, 0x35, 0x44, 0x60, 0x95, 0xca, 0xb5, 0x44, 0xe2, 0x5a, 0xaa,
	0x94, 0x01, 0x1c, 0x48, 0x19, 0x90, 0x98, 0xc8, 0x12, 0x15, 0x04, 0x02, 0xab, 0x62, 0x60, 0xb1,
	0x2e, 0xf5, 0xc3, 0x3a, 0x12, 0xfb, 0xdc, 0xbb, 0x73, 0x08, 0x13, 0x62, 0x40, 0xea, 0xc8, 0x67,
	0xe0, 0x43, 0xf0, 0x19, 0x3a, 0x22, 0xb1, 0x03, 0xca, 0x27, 0x41, 0xf6, 0x39, 0xae, 0xa0, 0x76,
	0x50, 0x33, 0xc0, 0xd0, 0xed, 0xee, 0xf9, 0xff, 0xbf, 0x7b, 0xef, 0x77, 0xef, 0x19, 0x1b, 0x44,
	0x4a, 0x4e, 0x47, 0x89, 0x04, 0xe1, 0x09, 0xc9, 0x38, 0x09, 0xc0, 0x89, 0x39, 0x93, 0x4c, 0xbf,
	0xf1, 0x86, 0x40, 0x00, 0xdc, 0x59, 0x44, 0xa7, 0x7d, 0xb3, 0x13, 0x30, 0x16, 0x4c, 0xa0, 0x97,
	0x09, 0x46, 0xc9, 0xeb, 0x9e, 0xa4, 0x21, 0x08, 0x49, 0xc2, 0x58, 0x79, 0xcc, 0xad, 0x80, 0x05,
	0x2c, 0x5b, 0xf6, 0xd2, 0x95, 0x8a, 0xda, 0x5f, 0x6a, 0x78, 0xe7, 0x51, 0x71, 0xcd, 0x8b, 0x04,
	0xf8, 0xbb, 0xe7, 0x84, 0x93, 0x10, 0x24, 0x70, 0xa1, 0xef, 0xe2, 0xe6, 0x5b, 0xc6, 0xc7, 0x22,
	0x26, 0x47, 0xe0, 0x51, 0xdf, 0x40, 0x16, 0xea, 0x6e, 0xb8, 0x9b, 0x45, 0xec, 0xc0, 0x4f, 0x25,
	0x02, 0xf8, 0x94, 0x1e, 0x81, 0x17, 0x91, 0x10, 0x8c, 0x9a, 0x92, 0xe4, 0xb1, 0x67, 0x24, 0x04,
	0x7d, 0x0f, 0xb7, 0x58, 0x0c, 0x9c, 0x48, 0xca, 0x22, 0x25, 0xaa, 0x67, 0xa2, 0x6b, 0x45, 0x34,
	0x93, 0x3d, 0xc6, 0x2d, 0x21, 0x09, 0x97, 0x5e, 0x9a, 0xb9, 0x17, 0xd2, 0xc8, 0x58, 0xb7, 0x50,
	0x77, 0xb3, 0x6f, 0x3a, 0xaa, 0x34, 0x67, 0x51, 0x9a, 0x73, 0xb8, 0x28, 0x6d, 0x70, 0xf5, 0xf4,
	0x7b, 0x67, 0xed, 0xd3, 0x8f, 0x0e, 0x72, 0x9b, 0x99, 0x37, 0xfd, 0xf2, 0x94, 0x46, 0x7f, 0x9e,
	0x45, 0x66, 0x86, 0xb6, 0xda, 0x59, 0x64, 0xa6, 0x6f, 0x61, 0x6d, 0x42, 0x43, 0x2a, 0x8d, 0x86,
	0x85, 0xba, 0x9a, 0xab, 0x36, 0xf6, 0x37, 0x84, 0xad, 0x21, 0xc8, 0x83, 0xc8, 0x87, 0x19, 0xf8,
	0x67, 0x08, 0xd3, 0x52, 0x84, 0x0b, 0xc7, 0x09, 0x08, 0xf9, 0x6f, 0xf9, 0x0d, 0xb0, 0x76, 0x9c,
	0xbe, 0x5f, 0x8e, 0xed, 0xb6, 0x73, 0xae, 0x49, 0x9c, 0xca, 0x97, 0x76, 0x95, 0xd5, 0xee, 0x63,
	0x73, 0x08, 0xf2, 0x5c, 0x35, 0x22, 0x66, 0x91, 0x80, 0x94, 0x44, 0x7a, 0xbd, 0x30, 0x90, 0x55,
	0xef, 0x6e, 0xb8, 0x6a, 0x63, 0x7f, 0xac, 0xe1, 0x5b, 0x43, 0x90, 0x87, 0x2c, 0x7e, 0x52, 0x18,
	0x5f, 0x92, 0x49, 0xf2, 0x9f, 0x30, 0xec, 0xe1, 0x56, 0x31, 0x37, 0x4a, 0xb6, 0xae, 0x64, 0x45,
	0xf4, 0x77, 0x5a, 0xda, 0xca, 0xb4, 0xf4, 0x26, 0x46, 0xe3, 0xbc, 0x2b, 0xd0, 0xd8, 0x7e, 0x80,
	0xdb, 0x55, 0x18, 0x72, 0x7e, 0xdb, 0xb8, 0x31, 0xcd, 0x22, 0x39, 0xc0, 0x7c, 0x67, 0x9f, 0xd4,
	0xb2, 0x5e, 0x1a, 0x30, 0x29, 0x59, 0x78, 0xb9, 0x21, 0x3e, 0xc4, 0xbb, 0x4b, 0x48, 0x2c, 0xe7,
	0xd8, 0xff, 0x5c, 0xc7, 0xd7, 0xcf, 0xee, 0x73, 0x81, 0xf8, 0xc0, 0xf5, 0x0f, 0x08, 0xef, 0x54,
	0x0e, 0xaa, 0xbe, 0x5f, 0x92, 0xf2, 0xdf, 0xc6, 0xda, 0xbc, 0x53, 0x6e, 0xaa, 0x18, 0x1b, 0x7b,
	0x4d, 0x7f, 0x8f, 0xb7, 0xcb, 0x5b, 0x43, 0xbf, 0x5b, 0x7e, 0x54, 0xf5, 0x30, 0x99, 0xf7, 0x2e,
	0xe0, 0x28, 0x12, 0x38, 0x51, 0x10, 0xca, 0xb9, 0x56, 0x41, 0x58, 0xda, 0x8f, 0xe6, 0xfd, 0x8b,
	0x99, 0x16, 0xa9, 0x0c, 0x6e, 0x9e, 0xce, 0xdb, 0xe8, 0xeb, 0xbc, 0x8d, 0x7e, 0xce, 0xdb, 0xe8,
	0xd5, 0x95, 0xdc, 0x3d, 0x6a, 0x64, 0x7f, 0xe4, 0xfd, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x61,
	0x88, 0x2a, 0xcb, 0xf5, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AttributesReaderClient is the client API for AttributesReader service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AttributesReaderClient interface {
	GetIndexedAttributesNames(ctx context.Context, in *GetIndexedAttributesNamesRequest, opts ...grpc.CallOption) (*GetAttributesNamesResponse, error)
	// GetTopKAttributeValues returns the most frequently observed values for an attribute.
	GetTopKAttributeValues(ctx context.Context, in *GetTopKAttributeValuesRequest, opts ...grpc.CallOption) (*GetTopKAttributeValuesResponse, error)
	// GetBottomKAttributeValues returns the least frequently observed values for an attribute.
	GetBottomKAttributeValues(ctx context.Context, in *GetBottomKAttributeValuesRequest, opts ...grpc.CallOption) (*GetBottomKAttributeValuesResponse, error)
}

type attributesReaderClient struct {
	cc *grpc.ClientConn
}

func NewAttributesReaderClient(cc *grpc.ClientConn) AttributesReaderClient {
	return &attributesReaderClient{cc}
}

func (c *attributesReaderClient) GetIndexedAttributesNames(ctx context.Context, in *GetIndexedAttributesNamesRequest, opts ...grpc.CallOption) (*GetAttributesNamesResponse, error) {
	out := new(GetAttributesNamesResponse)
	err := c.cc.Invoke(ctx, "/jaeger.storage.v2.AttributesReader/GetIndexedAttributesNames", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *attributesReaderClient) GetTopKAttributeValues(ctx context.Context, in *GetTopKAttributeValuesRequest, opts ...grpc.CallOption) (*GetTopKAttributeValuesResponse, error) {
	out := new(GetTopKAttributeValuesResponse)
	err := c.cc.Invoke(ctx, "/jaeger.storage.v2.AttributesReader/GetTopKAttributeValues", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *attributesReaderClient) GetBottomKAttributeValues(ctx context.Context, in *GetBottomKAttributeValuesRequest, opts ...grpc.CallOption) (*GetBottomKAttributeValuesResponse, error) {
	out := new(GetBottomKAttributeValuesResponse)
	err := c.cc.Invoke(ctx, "/jaeger.storage.v2.AttributesReader/GetBottomKAttributeValues", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AttributesReaderServer is the server API for AttributesReader service.
type AttributesReaderServer interface {
	GetIndexedAttributesNames(context.Context, *GetIndexedAttributesNamesRequest) (*GetAttributesNamesResponse, error)
	// GetTopKAttributeValues returns the most frequently observed values for an attribute.
	GetTopKAttributeValues(context.Context, *GetTopKAttributeValuesRequest) (*GetTopKAttributeValuesResponse, error)
	// GetBottomKAttributeValues returns the least frequently observed values for an attribute.
	GetBottomKAttributeValues(context.Context, *GetBottomKAttributeValuesRequest) (*GetBottomKAttributeValuesResponse, error)
}

// UnimplementedAttributesReaderServer can be embedded to have forward compatible implementations.
type UnimplementedAttributesReaderServer struct {
}

func (*UnimplementedAttributesReaderServer) GetIndexedAttributesNames(ctx context.Context, req *GetIndexedAttributesNamesRequest) (*GetAttributesNamesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIndexedAttributesNames not implemented")
}
func (*UnimplementedAttributesReaderServer) GetTopKAttributeValues(ctx context.Context, req *GetTopKAttributeValuesRequest) (*GetTopKAttributeValuesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTopKAttributeValues not implemented")
}
func (*UnimplementedAttributesReaderServer) GetBottomKAttributeValues(ctx context.Context, req *GetBottomKAttributeValuesRequest) (*GetBottomKAttributeValuesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBottomKAttributeValues not implemented")
}

func RegisterAttributesReaderServer(s *grpc.Server, srv AttributesReaderServer) {
	s.RegisterService(&_AttributesReader_serviceDesc, srv)
}

func _AttributesReader_GetIndexedAttributesNames_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIndexedAttributesNamesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttributesReaderServer).GetIndexedAttributesNames(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/jaeger.storage.v2.AttributesReader/GetIndexedAttributesNames",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttributesReaderServer).GetIndexedAttributesNames(ctx, req.(*GetIndexedAttributesNamesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AttributesReader_GetTopKAttributeValues_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTopKAttributeValuesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttributesReaderServer).GetTopKAttributeValues(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/jaeger.storage.v2.AttributesReader/GetTopKAttributeValues",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttributesReaderServer).GetTopKAttributeValues(ctx, req.(*GetTopKAttributeValuesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AttributesReader_GetBottomKAttributeValues_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBottomKAttributeValuesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttributesReaderServer).GetBottomKAttributeValues(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/jaeger.storage.v2.AttributesReader/GetBottomKAttributeValues",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttributesReaderServer).GetBottomKAttributeValues(ctx, req.(*GetBottomKAttributeValuesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AttributesReader_serviceDesc = grpc.ServiceDesc{
	ServiceName: "jaeger.storage.v2.AttributesReader",
	HandlerType: (*AttributesReaderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetIndexedAttributesNames",
			Handler:    _AttributesReader_GetIndexedAttributesNames_Handler,
		},
		{
			MethodName: "GetTopKAttributeValues",
			Handler:    _AttributesReader_GetTopKAttributeValues_Handler,
		},
		{
			MethodName: "GetBottomKAttributeValues",
			Handler:    _AttributesReader_GetBottomKAttributeValues_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "attributes_storage.proto",
}

func (m *AttributesQueryParameters) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AttributesQueryParameters) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AttributesQueryParameters) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Limit != 0 {
		i = encodeVarintAttributesStorage(dAtA, i, uint64(m.Limit))
		i--
		dAtA[i] = 0x30
	}
	n1, err1 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.StartTimeMax, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.StartTimeMax):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintAttributesStorage(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x2a
	n2, err2 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.StartTimeMin, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.StartTimeMin):])
	if err2 != nil {
		return 0, err2
	}
	i -= n2
	i = encodeVarintAttributesStorage(dAtA, i, uint64(n2))
	i--
	dAtA[i] = 0x22
	if len(m.OperationName) > 0 {
		i -= len(m.OperationName)
		copy(dAtA[i:], m.OperationName)
		i = encodeVarintAttributesStorage(dAtA, i, uint64(len(m.OperationName)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.ServiceName) > 0 {
		i -= len(m.ServiceName)
		copy(dAtA[i:], m.ServiceName)
		i = encodeVarintAttributesStorage(dAtA, i, uint64(len(m.ServiceName)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.WorkspaceId) > 0 {
		i -= len(m.WorkspaceId)
		copy(dAtA[i:], m.WorkspaceId)
		i = encodeVarintAttributesStorage(dAtA, i, uint64(len(m.WorkspaceId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GetIndexedAttributesNamesRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetIndexedAttributesNamesRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetIndexedAttributesNamesRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Query != nil {
		{
			size, err := m.Query.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintAttributesStorage(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if len(m.OperationName) > 0 {
		i -= len(m.OperationName)
		copy(dAtA[i:], m.OperationName)
		i = encodeVarintAttributesStorage(dAtA, i, uint64(len(m.OperationName)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.ServiceName) > 0 {
		i -= len(m.ServiceName)
		copy(dAtA[i:], m.ServiceName)
		i = encodeVarintAttributesStorage(dAtA, i, uint64(len(m.ServiceName)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.WorkspaceId) > 0 {
		i -= len(m.WorkspaceId)
		copy(dAtA[i:], m.WorkspaceId)
		i = encodeVarintAttributesStorage(dAtA, i, uint64(len(m.WorkspaceId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GetAttributesNamesResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetAttributesNamesResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetAttributesNamesResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.Names) > 0 {
		for iNdEx := len(m.Names) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Names[iNdEx])
			copy(dAtA[i:], m.Names[iNdEx])
			i = encodeVarintAttributesStorage(dAtA, i, uint64(len(m.Names[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *GetTopKAttributeValuesRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetTopKAttributeValuesRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetTopKAttributeValuesRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.K != 0 {
		i = encodeVarintAttributesStorage(dAtA, i, uint64(m.K))
		i--
		dAtA[i] = 0x30
	}
	if m.Query != nil {
		{
			size, err := m.Query.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintAttributesStorage(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	if len(m.AttributeName) > 0 {
		i -= len(m.AttributeName)
		copy(dAtA[i:], m.AttributeName)
		i = encodeVarintAttributesStorage(dAtA, i, uint64(len(m.AttributeName)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.OperationName) > 0 {
		i -= len(m.OperationName)
		copy(dAtA[i:], m.OperationName)
		i = encodeVarintAttributesStorage(dAtA, i, uint64(len(m.OperationName)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.ServiceName) > 0 {
		i -= len(m.ServiceName)
		copy(dAtA[i:], m.ServiceName)
		i = encodeVarintAttributesStorage(dAtA, i, uint64(len(m.ServiceName)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.WorkspaceId) > 0 {
		i -= len(m.WorkspaceId)
		copy(dAtA[i:], m.WorkspaceId)
		i = encodeVarintAttributesStorage(dAtA, i, uint64(len(m.WorkspaceId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GetTopKAttributeValuesResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetTopKAttributeValuesResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetTopKAttributeValuesResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.Values) > 0 {
		for iNdEx := len(m.Values) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Values[iNdEx])
			copy(dAtA[i:], m.Values[iNdEx])
			i = encodeVarintAttributesStorage(dAtA, i, uint64(len(m.Values[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *GetBottomKAttributeValuesRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetBottomKAttributeValuesRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetBottomKAttributeValuesRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.K != 0 {
		i = encodeVarintAttributesStorage(dAtA, i, uint64(m.K))
		i--
		dAtA[i] = 0x30
	}
	if m.Query != nil {
		{
			size, err := m.Query.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintAttributesStorage(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	if len(m.AttributeName) > 0 {
		i -= len(m.AttributeName)
		copy(dAtA[i:], m.AttributeName)
		i = encodeVarintAttributesStorage(dAtA, i, uint64(len(m.AttributeName)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.OperationName) > 0 {
		i -= len(m.OperationName)
		copy(dAtA[i:], m.OperationName)
		i = encodeVarintAttributesStorage(dAtA, i, uint64(len(m.OperationName)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.ServiceName) > 0 {
		i -= len(m.ServiceName)
		copy(dAtA[i:], m.ServiceName)
		i = encodeVarintAttributesStorage(dAtA, i, uint64(len(m.ServiceName)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.WorkspaceId) > 0 {
		i -= len(m.WorkspaceId)
		copy(dAtA[i:], m.WorkspaceId)
		i = encodeVarintAttributesStorage(dAtA, i, uint64(len(m.WorkspaceId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GetBottomKAttributeValuesResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetBottomKAttributeValuesResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetBottomKAttributeValuesResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.Values) > 0 {
		for iNdEx := len(m.Values) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Values[iNdEx])
			copy(dAtA[i:], m.Values[iNdEx])
			i = encodeVarintAttributesStorage(dAtA, i, uint64(len(m.Values[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintAttributesStorage(dAtA []byte, offset int, v uint64) int {
	offset -= sovAttributesStorage(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *AttributesQueryParameters) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.WorkspaceId)
	if l > 0 {
		n += 1 + l + sovAttributesStorage(uint64(l))
	}
	l = len(m.ServiceName)
	if l > 0 {
		n += 1 + l + sovAttributesStorage(uint64(l))
	}
	l = len(m.OperationName)
	if l > 0 {
		n += 1 + l + sovAttributesStorage(uint64(l))
	}
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.StartTimeMin)
	n += 1 + l + sovAttributesStorage(uint64(l))
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.StartTimeMax)
	n += 1 + l + sovAttributesStorage(uint64(l))
	if m.Limit != 0 {
		n += 1 + sovAttributesStorage(uint64(m.Limit))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *GetIndexedAttributesNamesRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.WorkspaceId)
	if l > 0 {
		n += 1 + l + sovAttributesStorage(uint64(l))
	}
	l = len(m.ServiceName)
	if l > 0 {
		n += 1 + l + sovAttributesStorage(uint64(l))
	}
	l = len(m.OperationName)
	if l > 0 {
		n += 1 + l + sovAttributesStorage(uint64(l))
	}
	if m.Query != nil {
		l = m.Query.Size()
		n += 1 + l + sovAttributesStorage(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *GetAttributesNamesResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Names) > 0 {
		for _, s := range m.Names {
			l = len(s)
			n += 1 + l + sovAttributesStorage(uint64(l))
		}
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *GetTopKAttributeValuesRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.WorkspaceId)
	if l > 0 {
		n += 1 + l + sovAttributesStorage(uint64(l))
	}
	l = len(m.ServiceName)
	if l > 0 {
		n += 1 + l + sovAttributesStorage(uint64(l))
	}
	l = len(m.OperationName)
	if l > 0 {
		n += 1 + l + sovAttributesStorage(uint64(l))
	}
	l = len(m.AttributeName)
	if l > 0 {
		n += 1 + l + sovAttributesStorage(uint64(l))
	}
	if m.Query != nil {
		l = m.Query.Size()
		n += 1 + l + sovAttributesStorage(uint64(l))
	}
	if m.K != 0 {
		n += 1 + sovAttributesStorage(uint64(m.K))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *GetTopKAttributeValuesResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Values) > 0 {
		for _, s := range m.Values {
			l = len(s)
			n += 1 + l + sovAttributesStorage(uint64(l))
		}
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *GetBottomKAttributeValuesRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.WorkspaceId)
	if l > 0 {
		n += 1 + l + sovAttributesStorage(uint64(l))
	}
	l = len(m.ServiceName)
	if l > 0 {
		n += 1 + l + sovAttributesStorage(uint64(l))
	}
	l = len(m.OperationName)
	if l > 0 {
		n += 1 + l + sovAttributesStorage(uint64(l))
	}
	l = len(m.AttributeName)
	if l > 0 {
		n += 1 + l + sovAttributesStorage(uint64(l))
	}
	if m.Query != nil {
		l = m.Query.Size()
		n += 1 + l + sovAttributesStorage(uint64(l))
	}
	if m.K != 0 {
		n += 1 + sovAttributesStorage(uint64(m.K))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *GetBottomKAttributeValuesResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Values) > 0 {
		for _, s := range m.Values {
			l = len(s)
			n += 1 + l + sovAttributesStorage(uint64(l))
		}
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovAttributesStorage(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozAttributesStorage(x uint64) (n int) {
	return sovAttributesStorage(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *AttributesQueryParameters) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAttributesStorage
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AttributesQueryParameters: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AttributesQueryParameters: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WorkspaceId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAttributesStorage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAttributesStorage
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAttributesStorage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WorkspaceId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ServiceName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAttributesStorage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAttributesStorage
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAttributesStorage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ServiceName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OperationName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAttributesStorage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAttributesStorage
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAttributesStorage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OperationName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartTimeMin", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAttributesStorage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAttributesStorage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAttributesStorage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.StartTimeMin, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartTimeMax", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAttributesStorage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAttributesStorage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAttributesStorage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.StartTimeMax, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Limit", wireType)
			}
			m.Limit = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAttributesStorage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Limit |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipAttributesStorage(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAttributesStorage
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetIndexedAttributesNamesRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAttributesStorage
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetIndexedAttributesNamesRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetIndexedAttributesNamesRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WorkspaceId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAttributesStorage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAttributesStorage
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAttributesStorage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WorkspaceId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ServiceName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAttributesStorage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAttributesStorage
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAttributesStorage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ServiceName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OperationName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAttributesStorage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAttributesStorage
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAttributesStorage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OperationName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Query", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAttributesStorage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAttributesStorage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAttributesStorage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Query == nil {
				m.Query = &AttributesQueryParameters{}
			}
			if err := m.Query.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAttributesStorage(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAttributesStorage
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetAttributesNamesResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAttributesStorage
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetAttributesNamesResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetAttributesNamesResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Names", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAttributesStorage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAttributesStorage
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAttributesStorage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Names = append(m.Names, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAttributesStorage(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAttributesStorage
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetTopKAttributeValuesRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAttributesStorage
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetTopKAttributeValuesRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetTopKAttributeValuesRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WorkspaceId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAttributesStorage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAttributesStorage
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAttributesStorage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WorkspaceId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ServiceName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAttributesStorage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAttributesStorage
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAttributesStorage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ServiceName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OperationName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAttributesStorage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAttributesStorage
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAttributesStorage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OperationName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AttributeName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAttributesStorage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAttributesStorage
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAttributesStorage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AttributeName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Query", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAttributesStorage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAttributesStorage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAttributesStorage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Query == nil {
				m.Query = &AttributesQueryParameters{}
			}
			if err := m.Query.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field K", wireType)
			}
			m.K = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAttributesStorage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.K |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipAttributesStorage(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAttributesStorage
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetTopKAttributeValuesResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAttributesStorage
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetTopKAttributeValuesResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetTopKAttributeValuesResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Values", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAttributesStorage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAttributesStorage
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAttributesStorage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Values = append(m.Values, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAttributesStorage(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAttributesStorage
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetBottomKAttributeValuesRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAttributesStorage
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetBottomKAttributeValuesRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetBottomKAttributeValuesRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WorkspaceId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAttributesStorage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAttributesStorage
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAttributesStorage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WorkspaceId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ServiceName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAttributesStorage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAttributesStorage
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAttributesStorage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ServiceName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OperationName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAttributesStorage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAttributesStorage
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAttributesStorage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OperationName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AttributeName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAttributesStorage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAttributesStorage
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAttributesStorage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AttributeName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Query", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAttributesStorage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAttributesStorage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAttributesStorage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Query == nil {
				m.Query = &AttributesQueryParameters{}
			}
			if err := m.Query.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field K", wireType)
			}
			m.K = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAttributesStorage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.K |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipAttributesStorage(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAttributesStorage
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetBottomKAttributeValuesResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAttributesStorage
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetBottomKAttributeValuesResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetBottomKAttributeValuesResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Values", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAttributesStorage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAttributesStorage
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAttributesStorage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Values = append(m.Values, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAttributesStorage(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAttributesStorage
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipAttributesStorage(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowAttributesStorage
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAttributesStorage
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAttributesStorage
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthAttributesStorage
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupAttributesStorage
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthAttributesStorage
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthAttributesStorage        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowAttributesStorage          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupAttributesStorage = fmt.Errorf("proto: unexpected end of group")
)
